name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2.16.0
      with:
        channel: stable
        flutter-version: 3.19.2

    - name: Install Dependencies
      run: flutter pub get

    - name: Run Tests
      run: flutter test

    - name: Build APK
      run: flutter build apk --release

    - name: Build iOS
      if: github.event_name == 'push' && runner.os == 'macOS'
      run: flutter build ios --release
